import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#faf8f5' },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#faf8f5' },
  list: { padding: 20, paddingBottom: 32, gap: 10 },
  title: { fontSize: 26, fontWeight: '800', color: '#2d2d2d', marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#2d2d2d', marginTop: 8, marginBottom: 10 },

  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: { fontSize: 14, fontWeight: '700', color: '#2d2d2d', marginBottom: 12 },

  upRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#f7f4ef',
    marginBottom: 8,
  },
  upRowFirst: { backgroundColor: '#f0ede6', borderWidth: 1, borderColor: '#e0dbd4' },
  upMonth: { fontSize: 13, fontWeight: '600', color: '#2d2d2d', textTransform: 'capitalize' },
  upDue: { fontSize: 12, color: '#aaa', marginTop: 2 },
  upAmount: { fontSize: 15, fontWeight: '700', color: '#2d2d2d' },
  upAdjust: { fontSize: 11, color: '#b45309', fontWeight: '600', marginTop: 1 },

  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 6 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#e0dbd4',
    backgroundColor: '#fff',
  },
  chipActive: { borderColor: '#6b5b45', backgroundColor: '#f0ede6' },
  chipText: { fontSize: 12, color: '#888', fontWeight: '600' },
  chipTextActive: { color: '#6b5b45' },

  empty: { textAlign: 'center', color: '#aaa', fontSize: 14, marginTop: 20 },

  payTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  payPeriod: { fontSize: 15, fontWeight: '700', color: '#2d2d2d', textTransform: 'capitalize' },
  payMeta: { fontSize: 12, color: '#888', marginTop: 4 },
  payNote: { fontSize: 12, color: '#666', fontStyle: 'italic', marginTop: 2 },
  payAmount: { fontSize: 19, fontWeight: '800', color: '#6b5b45', marginTop: 6 },
  payButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  payBtn: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0dbd4',
    backgroundColor: '#fff',
  },
  payBtnText: { fontSize: 12, fontWeight: '700', color: '#6b5b45' },
  payBtnMp: { backgroundColor: '#009ee3', borderColor: '#009ee3' },
  payBtnMpText: { fontSize: 12, fontWeight: '700', color: '#fff' },
  badge: { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3 },
  badgeText: { fontSize: 11, fontWeight: '700' },
  waitHint: { fontSize: 11, color: '#aaa', marginTop: 8 },

  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  pageBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0dbd4',
    backgroundColor: '#fff',
  },
  pageBtnDisabled: { opacity: 0.4 },
  pageBtnText: { fontSize: 13, color: '#6b5b45', fontWeight: '600' },
  pageInfo: { fontSize: 13, color: '#888' },

  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', padding: 24 },
  modalCard: { backgroundColor: '#fff', borderRadius: 16, padding: 22 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#2d2d2d' },
  modalSub: { fontSize: 13, color: '#888', marginTop: 4 },
  modalLabel: { fontSize: 13, fontWeight: '600', color: '#555', marginTop: 16, marginBottom: 6 },
  textarea: {
    borderWidth: 1,
    borderColor: '#e0dbd4',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#2d2d2d',
    minHeight: 70,
    textAlignVertical: 'top',
    backgroundColor: '#faf8f5',
  },
  transferData: { marginTop: 14 },
  transferRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0ebe4',
  },
  transferLabel: { fontSize: 11, color: '#aaa' },
  transferValue: { fontSize: 14, fontWeight: '700', color: '#2d2d2d' },
  copyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f0ede6',
  },
  copyBtnText: { fontSize: 12, fontWeight: '700', color: '#6b5b45' },
  contactRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  contactBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#f0ede6',
    alignItems: 'center',
  },
  contactBtnText: { fontSize: 13, fontWeight: '700', color: '#6b5b45' },
  contactBtnWa: { backgroundColor: '#25d366' },
  contactBtnWaText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
  modalCancel: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: '#f0ede6',
    alignItems: 'center',
  },
  modalCancelText: { color: '#888', fontSize: 14, fontWeight: '700' },
  modalConfirm: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: '#6b5b45',
    alignItems: 'center',
  },
  modalConfirmText: { color: '#fff', fontSize: 14, fontWeight: '700' },
});
